FROM node:16-alpine
WORKDIR /app

# Instalar dependências necessárias para o Firebase
RUN apk add --no-cache python3 make g++

# Copiar arquivos de dependências
COPY package*.json ./

# Instalar dependências
RUN npm install --production

# Copiar o resto dos arquivos
COPY . .

EXPOSE 3001
CMD [ "npm", "start" ]
